name: Container build
on: [workflow_dispatch]

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.acr_registry }}
          username: ${{ secrets.acr_username }}
          password: ${{ secrets.acr_password }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./dotnet/Dockerfile
          tags: ${{ secrets.acr_registry }}/vadimmmreg/hello:latest,${{ secrets.acr_registry }}/vadimmmreg/hello:$GITHUB_RUN_NUMBER